services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '${HTTP_PORT-80}:80' # Public HTTP Port
      - '${HTTPS_PORT-443}:443' # Public HTTPS Port
      - '${WEB_ADMIN_PORT-81}:81' # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  npm_data:
    name: ${VOLUME_NPM_DATA}
    external: true
  letsencrypt:
    name: ${VOLUME_LETSENCRYPT_DATA}
    external: true
