version: "3"
services:
  app:
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${HTTP_PORT}:80' # Public HTTP Port
      - '${HTTPS_PORT}:443' # Public HTTPS Port
      - '${WEB_ADMIN_PORT}:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # network_mode: host
    networks:
      - foo
      # - bar

networks:
  foo:
    external: true
    name: ${CLOUD_NETWORK}
