services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - le_data:/etc/letsencrypt

volumes:
  npm_data:
    name: ${VOLUME_NPM_DATA}
    external: true
  le_data:
    name: ${VOLUME_LETSENCRYPT_DATA}
    external: true
